// Plain-language explanations for jargon, surfaced on hover. "What it is + why it matters".
export const G = {
  fra: "Fire Risk Assessment — reviews fire safety of the building's common and internal areas, required under the Regulatory Reform (Fire Safety) Order 2005.",
  fraew: "Fire Risk Appraisal of External Walls (PAS 9980) — assesses the cladding and external wall build-up for fire risk.",
  overall: "The worse of the FRA and FRAEW ratings — the headline fire-risk position for this block.",
  totalActions: "All remedial actions recommended by the latest FRA.",
  overdueActions: "FRA remedial actions past their due date and not completed. A backlog signals required fire-safety works are slipping.",
  noDateActions: "Actions with no due date set — they can't be tracked for compliance and usually need chasing.",
  highActions: "Actions the assessor flagged as high priority / urgent.",
  inDate: "Whether the assessment is still within its validity period (typically 5 years from the assessment date).",
  assessmentType: "FRA scope: Type 1 (common parts, non-destructive) through Type 4 (destructive, includes flats).",
  bsa2022: "Building Safety Act 2022 — imposes stricter duties on Higher-Risk Buildings (18m+ or 7+ storeys).",
  mor: "Mandatory Occurrence Report — a safety event that must be reported to the Building Safety Regulator.",
  evacuation: "Planned fire response: 'stay put' (defend in place) vs 'simultaneous' (evacuate everyone) vs 'phased'.",
  compartmentation: "Fire-resisting division of the building that contains fire and smoke to limit spread.",
  pas9980: "Whether the external-wall appraisal followed the PAS 9980:2022 methodology.",
  clause14: "PAS 9980 Clause 14 fire-engineering analysis — invoked when the standard appraisal is inconclusive.",
  combustible: "Any external wall material that can contribute to fire spread.",
  acm: "Aluminium Composite Material — the Grenfell-type cladding; the highest fire concern.",
  hpl: "High-Pressure Laminate cladding — combustible.",
  eps: "Expanded polystyrene insulation — combustible.",
  pir: "Polyisocyanurate insulation — combustible.",
  phenolic: "Phenolic foam insulation — combustible.",
  mineralWool: "Mineral wool insulation — non-combustible (a positive sign).",
  bs8414: "Large-scale fire-test evidence (BS 8414) for the cladding system — critical when combustible cladding sits above 18m.",
  br135: "BR 135 fire-performance criteria — the pass/fail basis for a BS 8414 test.",
  cavityBarriers: "Barriers inside wall cavities that stop hidden fire and smoke spread.",
  fireBreaks: "Fire-stopping at floor levels and party walls to limit vertical and lateral spread.",
  dryRiser: "An empty pipe firefighters charge with water on arrival (buildings up to ~50m).",
  wetRiser: "A permanently charged firefighting water main (taller buildings).",
  heightSurvey: "A measured survey is recommended to confirm building height — it determines which regulations apply.",
  intrusive: "Opening-up of the wall is recommended to confirm its actual construction.",
  asbestos: "Asbestos is suspected behind the cladding — affects how and when remediation can proceed.",
  listed: "Statutory heritage protection — can constrain or delay remediation works.",
  tiv: "Total Insured Value — the sum insured across all units in this block.",
  confidence: "How confident the AI extraction was in reading this document (0–1).",
};
